version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    reviewers:
      - "antonengelhardt"
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    reviewers:
      - "antonengelhardt"
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: "docker"
    directory: "/docker"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    reviewers:
      - "antonengelhardt"
    commit-message:
      prefix: "chore(deps): "
