FROM python:3.8-buster

# install chromedriver
RUN apt update
RUN apt install chromium chromium-driver -y

# upgrade pip
RUN pip install --upgrade pip
COPY . /app
WORKDIR /app

# Install the Python requirements
RUN pip install -r requirements.txt

# Set the entrypoint to run the Python script
CMD ["python", "./main.py", "headless", "withZapier"]
