version: '3.7'

x-common:
  &common-settings
  build:
    context: .
    dockerfile: Dockerfile

services:
  kicktipp-bot:
    platform: linux/amd64
    <<: *common-settings
    container_name: kicktipp-bot
    restart: unless-stopped
    env_file: .env
