apiVersion: apps/v1
kind: Deployment
metadata:
  name: kicktipp-bot
  namespace: kicktipp-bot
  labels:
    app: kicktipp-bot

spec:
  selector:
    matchLabels:
      app: kicktipp-bot

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%

  replicas: 1

  template:
    metadata:
      labels:
        app: kicktipp-bot

    spec:
      imagePullSecrets:
        - name: ghcr

      containers:
        - name: kicktipp-bot
          image: ghcr.io/antonengelhardt/kicktipp-bot:refactor-v3-check
          imagePullPolicy: Always

          command: ["python3", "run.py", "--headless"]

          ports:
            - name: health
              containerPort: 8080
              protocol: TCP

          env:
            - name: PYTHONUNBUFFERED
              value: "1"

          envFrom:
            - configMapRef:
                name: kicktipp-bot-config
            - secretRef:
                name: kicktipp-bot-secrets

          # Startup probe - allows container time to start up
          startupProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1

          # Liveness probe - restarts container if unhealthy
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1

          # Readiness probe - controls traffic routing
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 1

          resources:
            requests:
              cpu: 250m
              memory: 400Mi
            limits:
              cpu: 500m
              memory: 800Mi

      restartPolicy: Always
