apiVersion: v1
kind: Service
metadata:
  name: kicktipp-bot-health
  namespace: kicktipp-bot
  labels:
    app: kicktipp-bot
spec:
  selector:
    app: kicktipp-bot
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
  type: ClusterIP
---
# Optional: ServiceMonitor for Prometheus monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kicktipp-bot-monitor
  namespace: kicktipp-bot
  labels:
    app: kicktipp-bot
spec:
  selector:
    matchLabels:
      app: kicktipp-bot
  endpoints:
    - port: health
      path: /status
      interval: 30s
      scrapeTimeout: 10s
