version: '3.7'

services:
  kicktipp-bot:
    container_name: kicktipp-bot
    image: ghcr.io/antonengelhardt/kicktipp-bot:amd64
    platform: linux/amd64
    tty: true
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8080:8080"  # Health check port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
