name: PR checks

on:
  pull_request:

jobs:
  build:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Login to DockerHub
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

    - name: Build and push amd64 Docker image
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: linux/amd64
        tags: ghcr.io/antonengelhardt/kicktipp-bot:pr-${{ github.event.number }}-amd64

    # - name: Build and push arm64 Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: true
    #     platforms: linux/arm64
    #     tags: ghcr.io/antonengelhardt/kicktipp-bot:arm64
